### ISSUE TITLE
Setting option `debug:true` does not result in any additional logs in console

### ISSUE THREAD

**Issue by nurazem** [Moesif/moesif-browser-js#1]
I have noticed that there are supposed to be a bunch of messages printed out to console during the initialization of the `moesif-browser-js` client. No messages are printed to the console regardless of setting `debug: true`  in initialization options. This happens both when using the library through npm or a CDN.

**Comment by xinghengwang** [comment]
actually, this is by design. The debug option isn't available on the optimized code, since we use very aggressive optimization to minimize the code size for the front end.  So if you clone this repo, then edit, `src/config.js`, to set debug to true, then run `npm run build` to recompile and build everything, the debug flag would be on. Then that `src/config.js` debug is set to false, the aggressive compression algorithm removes all code regarding to print lines.
